language: node_js

matrix:
  include:
    - node_js: "10"
    - node_js: "11"
    - node_js: "12"
    - node_js: "13"

install:
  - npm install

script:
  - ./node_modules/mocha/bin/mocha tests --timeout 30000
